resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: chrom-works-secret
    type: kubernetes.io/tls
    files:
      - tls.crt=secrets/tls.crt
      - tls.key=secrets/tls.key
